### ISSUE TITLE
Problems with ParseSMILES - missing add_vertex method

### ISSUE THREAD

**Issue by Leticia-maria** [caseykneale/OpenSMILES.jl#15]
I've tested th package and the command `Graph = OpenSMILES.ParseSMILES("C1=CC=C2C(=C1)C(=CN2)CC(C(=O)O)N")` crashed. (Error message attached)
![Screenshot from 2021-11-02 09-35-10](https://user-images.githubusercontent.com/60739184/139848002-06efaa04-0001-4c1b-9a18-74b5d5769628.png)

**Comment by caseykneale** [comment]
Interesting, thats a new error for me. Whats interesting about that is - it definitely used to work. So the most likely issue is something isn't phrased right for a change in a dependency. Maybe try downgrading light graphs? An issue that's come up in general is that the LightGraphs package has been abandoned iirc. Which is unfortunate.

This package isn't under active development (by me) at this point in time due to "life" reasons. If I get time I'll go back and fix it. Alternatively, depending on what you want, there are other SMILES parsers in the ecosystem and in nearby languages. 

Also - if I could go back in time, I would have written an actual parser for this package. This was something I threw together on a Saturday morning. So the next version may just be a rewrite...

**Comment by Leticia-maria** [comment]
Thank you for replying me. If you are interested, I could try helping to rewrite this and eliminate this dependencies in a new version.

**Comment by timholy** [comment]
Personally I recommend MolecularGraphs. It's why I stopped pushing this package forward.

**Comment by Leticia-maria** [comment]
Yes, of course😊. Actually I am using MolecularGraphs in my project. I was only testing this one to check another option.

**Comment by caseykneale** [comment]
If you want to rewrite anything here - you will receive no consternation from me! The only thing I ask is that unit tests pass(ideally similar to the ones that exist). Then again - it sounds like they aren't passing now due to compat oversight - so, beggers cannot be choosers :p. I think a finite state machine parsing pattern, or even leveraging something else from the ecosystem could be a lot of fun! 

There are advantages to rolling your own parser for performance/analysis reasons. If you want cool project ideas - I have too many to count.

I agree, MolecularGraphs seems like a good way forward(there's a stub on the readme of this referring people too it). That said - it seems like factoring out parsers to separate packages would be the Julian approach. I have no involvement in the Julia ecosystem at this time (unfortunately) due to job/life constraints, but there's many ways to approach this.

**Comment by caseykneale** [comment]
For context, this was a small piece of a much larger project(which was only somewhat successful). This didn't get the attention it deserved on the first pass, but it was functional so I cut a release.

**Comment by caseykneale** [comment]
Also I can make you a contributor or whatever you want. I'm anarchistic for pretty much all OSS stuff.

**Comment by Leticia-maria** [comment]
I'd like to be a contributor, if you are interested in. I think this project has a lot of potential. As much tools as we have, molecular representations are never enough, they need always being improved.

**Comment by caseykneale** [comment]
You've been invited to be a collaborator :). Have fun, and feel free to ask for help or whatever. I can't full time do much of anything but once in a while I can do something.

**Comment by caseykneale** [comment]
Actually had a good idea for a pattern for this that would probably solve this problem and another very very cleanly. Performance should be relatively good too. I don't know if/when I'll be able to work on it, but stay tuned...

**Comment by caseykneale** [comment]
I think your problem is to do with Graphs.jl potentially. Graph.jl has broken add_vertex method. Once that's fixed I'll consider working on this again. MolecularGraphs was smart to use their own graph API.

https://github.com/JuliaGraphs/Graphs.jl/issues/38

**Comment by Leticia-maria** [comment]
I will look at this on weekend. We can keep in contact to fix it.

**Comment by caseykneale** [comment]
Think this PR just needs to be rolled back: https://github.com/caseykneale/OpenSMILES.jl/pull/14/commits/65321bfb2d8e454df583ed5119e41941d5ffe8b6

**Comment by caseykneale** [comment]
This has been fixed :).
